owner: benjamin-hx
repo: statuspage

sites:
  - name: Holiday Extras
    url: https://www.holidayextras.com
  - name: Google
    url: https://www.google.com
  - name: Ouline
    url: https://holidayextras.getoutline.com
  - name: Slack
    url: https://slack.com
  - name: Jira
    url: https://holidayextras.jira.com

status-website:
  baseUrl: /statuspage
  logoUrl: https://www.google.com/u/0/ac/images/logo.gif?uid=108578596573238218857&service=google_gsuite
  name: Status Page
  introTitle: "Uptime monitor and status page"
  introMessage: "Holiday Extras System Status: Stay informed about the current health of our services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean

i18n:
  url: "URL"
  status: "Status"
  history: "History"
  responseTime: "Response Time"
  uptime: "Uptime"
  up: "游릴 Up"
  degraded: "游릳 Degraded"
  down: "游린 Down"
  responseTimeGraphAlt: "Response time graph"
  ms: "ms"
  responseTime: "Response time"
  responseTimeDay: "24-hour response time"
  responseTimeWeek: "7-day response time"
  responseTimeMonth: "30-day response time"
  responseTimeYear: "1-year response time"
  uptime: "All-time uptime"
  uptimeDay: "24-hour uptime"
  uptimeWeek: "7-day uptime"
  uptimeMonth: "30-day uptime"
  uptimeYear: "1-year uptime"
  liveStatus: "Live Status"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "游릴 All systems operational"
  degradedPerformance: "游릳 Degraded performance"
  completeOutage: "游린 Complete outage"
  partialOutage: "游릲 Partial outage"
  footer: Project Lab Day 08/04/2025
