owner: benjamin-hx
repo: statuspage

sites:
  - name: Holiday Extras
    url: https://www.holidayextras.com
  - name: Google
    url: https://www.google.com
  - name: Ouline
    url: https://holidayextras.getoutline.com
  - name: Slack
    url: https://slack.com
  - name: Jira
    url: https://holidayextras.jira.com
  - name: Gemini
    url: https://gemini.google.com
  - name: ChatGPT
    url: https://openai.com


status-website:
  baseUrl: /statuspage
  logoUrl: https://www.google.com/u/0/ac/images/logo.gif?uid=108578596573238218857&service=google_gsuite
  name: Status Page
  introTitle: "Uptime monitor and status page"
  introMessage: "Holiday Extras System Status: Stay informed about the current health of our services."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean

i18n:
  footer: Project Lab Day 08/04/2025
